services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ThinkDigital\ContaoFontAwesomeInsertTags\:
        resource: '../../*'
        exclude:
            - '../../ContaoManager/'
            - '../../DependencyInjection/'
            - '../../ContaoFontAwesomeInsertTagsBundle.php'
